site: Andrew Violette
email: andrew@andrewviolette.net
url: https://www.andrewviolette.net
baseurl: ""
github_username:  aviolette
description: Come hither where I will talk about technology, booze, and other stuff that interests me.
# Layout

show_social: false          # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header

# Menu

navigation:
  - {title: "Andrew Violette", url: "/", icon: home}
  - {title: "Resume", url: "https://www.andrewviolette.net/AJVResume-Jan2021.pdf", icon: file}

external:                  # see http://fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/aviolette"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
